python shell/user_analysis.py data app_log_update
python shell/user_analysis.py data ts_order
python shell/user_analysis.py data ts_holding
python shell/user_analysis.py data user_log
python shell/user_analysis.py data all_feature
python shell/user_analysis.py data user_redeem_train_feature
python shell/user_analysis.py data user_buy_train_feature
python shell/user_analysis.py train user_buy_xgboost
python shell/user_analysis.py train user_redeem_xgboost
