#!/bin/bash

nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114001 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114002 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114003 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114004 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114005 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114006 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114007 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114008 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114009 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114010 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114011 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114012 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114013 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114014 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114015 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114016 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114017 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114018 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114019 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114020 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114021 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114022 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114023 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114024 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114025 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114026 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114027 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool nav --id 11114028 2>&1 &

nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114001 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114002 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114003 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114004 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114005 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114006 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114007 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114008 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114009 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114010 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114011 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114012 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114013 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114014 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114015 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114016 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114017 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114018 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114019 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114020 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114021 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114022 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114023 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114024 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114025 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114026 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114027 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool turnover --id 11114028 2>&1 &
