#!/bin/bash

nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114001 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114002 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114003 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114004 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114005 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114006 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114007 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114008 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114009 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114010 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114011 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114012 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114013 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114014 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114015 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114016 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114017 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114018 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114019 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114020 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114021 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114022 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114023 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114024 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114025 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114026 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114027 --limit 10 2>&1 &
nohup python3 /home/yaojiahui/recommend_model2/recommend_model/asset_allocation_v2/shell/roboadvisor.py pool fund_factor_pool --id 11114028 --limit 10 2>&1 &
